language: php

php:
  - 5.4
  - 5.5
  - 5.6

sudo: false

install:
  - yes '' | pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --prefer-source --no-interaction

script: 
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
